logging:
  level:
    org.springframework.security: trace
    org.hibernate.SQL: DEBUG

# spring:
#   datasource:
#     url: jdbc:postgresql://localhost:5432/oauth2db
#     username: postgres
#     password: root

#   jpa:
#     hibernate:
#      ddl-auto: update

server:
  port: 9090

jwtUri: http://localhost:8080/oauth2/jwks  
